name: Build and deploy ASP app to Azure Web App - kuberno-example-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Azure Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" \
        working-directory: infra

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan
        working-directory: infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: infra

      - name: Export Terraform Output
        run: terraform output -json > tf_outputs.json
        working-directory: infra

      - name: Upload Terraform Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-outputs
          path: infra/tf_outputs.json

  build:
    name: Build ASP.NET application
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: "/published/**"

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs:
      - build
      - terraform
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Terraform Output Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-outputs
          path: ./infra-output

      - name: Read random_suffix from output
        id: tf
        run: |
          $output = Get-Content ./infra-output/tf_outputs.json | ConvertFrom-Json
          echo "web_app_name=$($output.web_app_name.value)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./publish-folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.web_app_name }}
          package: ./publish-folder
