# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - kuberno-example-app-ciiwfdggi6hp1ci4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: "/published/**"

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./publish-folder

      - name: Zip site contents
        run: Compress-Archive -Path "./publish-folder/*" -DestinationPath "publish.zip"

      - name: Deploy to Azure using Zip Deploy
        run: |
          curl -X POST "https://${{ secrets.WEB_APP_NAME }}.scm.azurewebsites.net/api/zipdeploy" `
            --user ${{ secrets.KUDU_USERNAME }}:${{ secrets.KUDU_PASSWORD }} `
            --header "Content-Type: application/zip" `
            --data-binary "@publish.zip"
